const data = [
  {
    id: "component-1",
    title: "X-ray instrument",
    description:
      "Sending a telescope to space means engineering for the impossible: it has to survive a rocket launch, then operate flawlessly in a vacuum where temperatures swing by hundreds of degrees. NEBULA-Xplorer's X-ray instrument does exactly that, suspended on three precision titanium mounts that isolate it from every shock and temperature change, anchored to a reinforced panel strong enough to carry its weight, and oriented to make full use of every centimeter of space inside the rocket fairing.",
  },
  {
    id: "component-2",
    title: "Batteries",
    description:
      "Every time NEBULA-Xplorer passes into the shadow of the Earth, the Sun disappears, and the spacecraft has to keep running on stored power alone. For up to 35 minutes per orbit, the battery packs are the only thing keeping the telescope alive. Positioned at the top of the bus and carefully isolated from the rest of the spacecraft to stay within their required temperature range, they're engineered to charge and discharge tens of thousands of times over the mission's lifetime without significant loss of capacity.",
  },
  {
    id: "component-3",
    title: "Star tracker module",
    description:
      "To observe a faint X-ray source hundreds of light-years away, NEBULA-Xplorer needs to hold its aim with extraordinary precision. Star trackers continuously scan the sky, recognize patterns of stars, and determine the spacecraft’s orientation down to a few arcseconds. Two units ensure constant visibility of stars even during rotation.",
  },
  {
    id: "component-4",
    title: "Bus subsystem mounting rack",
    description:
      "A rack of electronics manages power distribution, system control, and communication. It routes energy from solar arrays and enables high-speed data transmission to Earth during short communication windows, making it the operational backbone of the mission.",
  },
  {
    id: "component-5",
    title: "Dawn 4U Cubedrive",
    description:
      "The propulsion system counters atmospheric drag, performs collision avoidance, and enables controlled reentry. This compact thruster unit carries under two kilograms of propellant and is precisely aligned to ensure stable and accurate maneuvers throughout the mission.",
  },
  {
    id: "component-6",
    title: "S-band Antenna",
    description:
      "The S-band antenna enables communication with Earth during brief contact windows. It transmits gigabytes of scientific data over large distances in just minutes, ensuring valuable observations reach ground stations.",
  },
  {
    id: "component-7",
    title: "GNSS Receiver",
    description:
      "The GNSS receiver provides precise timing and positioning, accurate to microseconds and within 30 meters. This ensures that X-ray detections can be scientifically interpreted with exact spatial and temporal context.",
  },
  {
    id: "component-8",
    title: "Sun sensor",
    description:
      "Sun sensors provide basic orientation by detecting the Sun’s position. They are crucial during emergencies or initial deployment, helping the spacecraft maintain power and avoid dangerous pointing scenarios.",
  },
  {
    id: "component-9",
    title: "Instrument electronics module",
    description:
      "This module captures and processes tiny voltage pulses generated by incoming X-ray photons. It measures their energy and timestamps them with microsecond precision, converting raw signals into usable scientific data.",
  },
  {
    id: "component-10",
    title: "Magnetometers",
    description:
      "Two magnetometers measure Earth’s magnetic field, enabling the spacecraft to use magnetic torquers for momentum control. They help maintain stability without using propellant.",
  },
  {
    id: "component-11",
    title: "SADM",
    description:
      "The Solar Array Drive Mechanism allows solar panels to track the Sun independently of the telescope’s orientation, ensuring continuous power generation while observing different targets.",
  },
  {
    id: "component-12",
    title: "Reaction wheel module",
    description:
      "Reaction wheels control the spacecraft’s orientation by exchanging angular momentum. They enable precise pointing and smooth rotations without using thrusters, essential for stable observations.",
  },
  {
    id: "component-13",
    title: "OBC, TCM, and inertial measurement unit",
    description:
      "The onboard computer, inertial measurement unit, and control modules form the spacecraft’s brain and nervous system. They manage operations, track movement, and ensure autonomous decision-making in orbit.",
  },
];

// select all HTML elements
const inputFields = document.querySelector("form");
const infoTitle = document.querySelector(".info-box h3");
const infoText = document.querySelector(".info-box p");
const container = document.querySelector(".container");

// event listener (maar 1 keer nodig)
inputFields.addEventListener("change", (e) => {
  const inputId = e.target;
  const infoBoxData = getMatchingData(inputId);

  // check of er data is (voorkomt errors)
  if (!infoBoxData) return;

  // change title and description
  infoTitle.textContent = infoBoxData.title;
  infoText.textContent = infoBoxData.description;

  // hide scroll & drag
  if (container) {
    container.style.display = "none";
  }
});

// function om data te matchen
function getMatchingData(element) {
  const itemId = element.id;

  const jsonMatch = data.find((i) => i.id === itemId);

  // als niks gevonden wordt → return null
  if (!jsonMatch) return null;

  return {
    title: jsonMatch.title,
    description: jsonMatch.description
  };
}
